import * as THREE from 'three';
import { PointerLockControls } from 'three/addons/controls/PointerLockControls.js';
import { createErlingRig, animateErling, disposeErlingRig, addSchoolWallArt } from './fps-visuals.js?v=20260905-art1';
import { createGunnarTexture, createGunnarRig, animateGunnar, disposeGunnarRig } from './fps-gunnar.js?v=20260907-gunnar1';

const canvas=document.getElementById('game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8eb5c4);scene.fog=new THREE.Fog(0x8eb5c4,36,78);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.08,110);camera.position.set(0,1.7,18);
const controls=new PointerLockControls(camera,document.body);scene.add(camera);
scene.add(new THREE.HemisphereLight(0xdcefff,0x62594c,2.4));const sun=new THREE.DirectionalLight(0xfff1cf,2.6);sun.position.set(-18,28,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-45;sun.shadow.camera.right=45;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-45;scene.add(sun);

const WORLD=54,WALL_H=3.7,PLAYER_R=.48,EYE=1.7;const colliders=[];let erlingTexture=null;const gunnarTexture=createGunnarTexture();
function makeTransparentErlingTexture(image){const c=document.createElement('canvas');c.width=image.naturalWidth||image.width;c.height=image.naturalHeight||image.height;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,c.width,c.height);const img=ctx.getImageData(0,0,c.width,c.height),data=img.data,w=c.width,h=c.height;const seen=new Uint8Array(w*h),stack=[];const nearWhite=i=>{const p=i*4,r=data[p],g=data[p+1],b=data[p+2];return r>215&&g>207&&b>185&&Math.max(r,g,b)-Math.min(r,g,b)<45;};const push=(x,y)=>{if(x<0||y<0||x>=w||y>=h)return;const i=y*w+x;if(seen[i]||!nearWhite(i))return;seen[i]=1;stack.push(i);};for(let x=0;x<w;x++){push(x,0);push(x,h-1);}for(let y=0;y<h;y++){push(0,y);push(w-1,y);}push(Math.floor(w*.30),Math.floor(h*.49));push(Math.floor(w*.68),Math.floor(h*.46));push(Math.floor(w*.47),Math.floor(h*.81));while(stack.length){const i=stack.pop(),x=i%w,y=(i/w)|0,p=i*4;data[p+3]=0;push(x+1,y);push(x-1,y);push(x,y+1);push(x,y-1);}ctx.putImageData(img,0,0);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.needsUpdate=true;return t;}
const startButton=document.getElementById('start-button');
function loadErling(){startButton.disabled=true;startButton.textContent='ERLING ER PÅ VEJ…';new THREE.TextureLoader().load('assets/figurer/erling-aergerlig.webp',tex=>{erlingTexture=makeTransparentErlingTexture(tex.image);tex.dispose();startButton.disabled=false;startButton.textContent='IND PÅ SKOLEN';},undefined,()=>{startButton.disabled=false;startButton.textContent='HENT ERLING IGEN';});}loadErling();

function mat(color){return new THREE.MeshStandardMaterial({color,roughness:.82,metalness:.02});}const floorMat=mat(0xc8b992),wallMat=mat(0xe7dfc8),trimMat=mat(0x375d67),deskMat=mat(0x9a633e),lockerMat=mat(0x66838a);
function box(x,y,z,w,h,d,material=wallMat,solid=true){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;scene.add(m);if(solid)colliders.push(new THREE.Box3().setFromObject(m));return m;}
box(0,-.12,0,WORLD,.24,WORLD,floorMat,false);box(0,WALL_H/2,-WORLD/2,WORLD,WALL_H,.45);box(0,WALL_H/2,WORLD/2,WORLD,WALL_H,.45);box(-WORLD/2,WALL_H/2,0,.45,WALL_H,WORLD);box(WORLD/2,WALL_H/2,0,.45,WALL_H,WORLD);
[[-13,-17,18,.35],[-13,1,18,.35],[-13,20,14,.35],[13,-20,13,.35],[13,-4,13,.35],[13,13,18,.35],[-20,-10,.35,13],[-5,-10,.35,13],[10,-10,.35,11],[22,-10,.35,9],[-21,10,.35,14],[-6,10,.35,12],[9,10,.35,10],[21,10,.35,11]].forEach(([x,z,w,d])=>box(x,WALL_H/2,z,w,WALL_H,d,wallMat));
box(-26,1.15,-2,.08,1.25,8,trimMat,false);box(26,1.15,5,.08,1.25,9,trimMat,false);box(-19,1.65,-26.7,8,1.55,.08,mat(0x29483e),false);box(19,1.65,26.7,8,1.55,.08,mat(0x29483e),false);
[[-20,-19],[-16,-19],[-20,-15],[-16,-15],[18,-18],[22,-18],[18,-14],[22,-14],[-20,18],[-16,18],[-20,22],[-16,22],[18,17],[22,17],[18,21],[22,21]].forEach(([x,z])=>{box(x,.55,z,2.3,.12,1.25,deskMat,true);box(x-.85,.27,z,.12,.55,1,deskMat,true);box(x+.85,.27,z,.12,.55,1,deskMat,true);});for(let z=-20;z<=20;z+=2.2)box(-25.4,1,z,.8,2,1.7,lockerMat,true);for(let z=-21;z<=21;z+=7){box(0,3.48,z,4,.08,.7,mat(0xf6e6ae),false);const light=new THREE.PointLight(0xffe8ad,.85,10);light.position.set(0,3.15,z);scene.add(light);}addSchoolWallArt(scene,renderer);

const keys={};let vy=0,onGround=true,last=performance.now(),lives=5,ammo=0,score=0,erlingKills=0,answer='',gameActive=false,problem=null,invulnerableUntil=0;
let enemies=[],projectiles=[],spawnVoiceIndex=0,moveVoiceIndex=0,gunnarVoiceIndex=0,lastMoveVoiceAt=0,musicMuted=false,audioCtx=null,musicGain=null,musicTimer=null,musicStep=0;
let campBoost=false,lastPlayerMoveAt=performance.now(),campMovementStartedAt=0;
let magicCircle=null,magicCircleTriggered=false,divisionChallenge=null;
const livesEl=document.getElementById('lives'),ammoEl=document.getElementById('ammo'),scoreEl=document.getElementById('score'),problemEl=document.getElementById('problem'),answerEl=document.getElementById('answer'),feedbackEl=document.getElementById('feedback'),mathKickerEl=document.querySelector('.math-kicker');
const rand=(min,max)=>Math.floor(Math.random()*(max-min+1))+min;

function normalProblem(){const a=rand(1,9),b=rand(1,9);return {kind:'multiply',expression:`${a} × ${b}`,answer:a*b};}
function divisionProblem(){const divisor=rand(1,9),quotient=rand(1,9);return {kind:'division',expression:`${divisor*quotient} ÷ ${divisor}`,answer:quotient};}
function newProblem(){if(divisionChallenge?.active)return;problem=normalProblem();mathKickerEl.textContent='ERLINGS GANGESTYKKE';problemEl.textContent=problem.expression;answer='';answerEl.textContent='_';feedbackEl.textContent='Svar rigtigt for at få en blyant. · M = musik';feedbackEl.className='feedback';}
function pickSpawnPosition(){const candidates=[[-21,-22],[20,-22],[-20,22],[20,22],[0,-23],[0,23],[-23,0],[23,0],[-7,-22],[8,22]];const valid=candidates.filter(p=>new THREE.Vector2(p[0]-camera.position.x,p[1]-camera.position.z).length()>11);const pool=valid.length?valid:candidates,p=pool[Math.floor(Math.random()*pool.length)];return new THREE.Vector3(p[0]+(Math.random()-.5)*2.4,0,p[1]+(Math.random()-.5)*2.4);}
function createErling(){const enemy=createErlingRig(erlingTexture);enemy.type='erling';enemy.hp=1;enemy.maxHp=1;enemy.speed=1.35;enemy.group.position.copy(pickSpawnPosition());scene.add(enemy.group);enemies.push(enemy);return enemy;}
function createGunnar(){const enemy=createGunnarRig(gunnarTexture);enemy.group.position.copy(pickSpawnPosition());scene.add(enemy.group);enemies.push(enemy);speakGunnar();return enemy;}
function removeEnemy(enemy){const i=enemies.indexOf(enemy);if(i>=0)enemies.splice(i,1);if(enemy.type==='gunnar')disposeGunnarRig(enemy);else disposeErlingRig(enemy);scene.remove(enemy.group);}
function clearEnemies(){[...enemies].forEach(removeEnemy);}

function speakLine(text,opts={}){if(!('speechSynthesis' in window))return;const u=new SpeechSynthesisUtterance(text);u.lang='da-DK';u.rate=opts.rate||.86;u.pitch=opts.pitch||.68;u.volume=opts.volume||.92;const voices=speechSynthesis.getVoices();const danish=voices.find(v=>/^da(-|_)/i.test(v.lang))||voices.find(v=>/danish/i.test(v.name));if(danish)u.voice=danish;speechSynthesis.speak(u);}
function speakSpawn(){const lines=['Nu kommer Erling!','Ned med de dygtige!'];speakLine(lines[spawnVoiceIndex++%lines.length],{rate:.82,pitch:.64,volume:.96});}
function speakGunnar(){const lines=['Jeg er den seje!','Giv mig din madpakke!','Gunnar in the house!'];speakLine(lines[gunnarVoiceIndex++%lines.length],{rate:.92,pitch:.76,volume:.98});}
function maybeSpeakWhileMoving(now){if(divisionChallenge?.active||now-lastMoveVoiceAt<5600||!('speechSynthesis' in window)||speechSynthesis.speaking)return;lastMoveVoiceAt=now;if(enemies.some(e=>e.type==='gunnar')){speakGunnar();return;}if(enemies.some(e=>e.type==='erling')){const lines=['Nu har jeg dig!','Jeg slapper din matematik-eksamen!','Du skal være et nul ligesom mig!'];speakLine(lines[moveVoiceIndex++%lines.length],{rate:.88,pitch:.67,volume:.9});}}
function spawnWave(count=1,announce=true){for(let i=0;i<count;i++)createErling();if(announce)speakSpawn();}

function ensureMusic(){if(audioCtx)return;audioCtx=new (window.AudioContext||window.webkitAudioContext)();musicGain=audioCtx.createGain();musicGain.gain.value=musicMuted?0:.12;musicGain.connect(audioCtx.destination);const bass=[55,55,65.41,55,73.42,65.41,55,49],lead=[220,261.63,293.66,329.63,293.66,261.63,220,196];musicTimer=setInterval(()=>{if(!gameActive||musicMuted||audioCtx.state!=='running')return;const now=audioCtx.currentTime;const hit=(freq,duration,type,gainValue)=>{const osc=audioCtx.createOscillator(),g=audioCtx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(gainValue,now);g.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(g);g.connect(musicGain);osc.start(now);osc.stop(now+duration);};hit(bass[musicStep%bass.length],.19,'sawtooth',.5);if(musicStep%2===0)hit(lead[musicStep%lead.length],.11,'square',.18);musicStep++;},170);}
function toggleMusic(){musicMuted=!musicMuted;if(musicGain)musicGain.gain.setTargetAtTime(musicMuted?0:.12,audioCtx.currentTime,.03);feedbackEl.textContent=musicMuted?'Musik: SLUKKET (M)':'Musik: TÆNDT (M)';feedbackEl.className='feedback';}

function makePencil(){const group=new THREE.Group();const wood=new THREE.MeshStandardMaterial({color:0xf4b522,roughness:.6}),graphite=new THREE.MeshStandardMaterial({color:0x292929,roughness:.8}),pink=new THREE.MeshStandardMaterial({color:0xdb7f8e,roughness:.65}),metal=new THREE.MeshStandardMaterial({color:0xb7a986,roughness:.4,metalness:.5});const body=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,.9,8),wood);body.rotation.z=Math.PI/2;group.add(body);const ferrule=new THREE.Mesh(new THREE.CylinderGeometry(.062,.062,.14,10),metal);ferrule.rotation.z=Math.PI/2;ferrule.position.x=-.51;group.add(ferrule);const eraser=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,.16,10),pink);eraser.rotation.z=Math.PI/2;eraser.position.x=-.66;group.add(eraser);const tip=new THREE.Mesh(new THREE.ConeGeometry(.08,.24,10),wood);tip.rotation.z=-Math.PI/2;tip.position.x=.57;group.add(tip);const lead=new THREE.Mesh(new THREE.ConeGeometry(.032,.09,8),graphite);lead.rotation.z=-Math.PI/2;lead.position.x=.72;group.add(lead);group.scale.setScalar(1.35);return group;}
function firePencil(){if(!gameActive||!controls.isLocked||ammo<=0||divisionChallenge?.active)return;ammo--;updateHUD();flash('shot-flash');const dir=new THREE.Vector3();camera.getWorldDirection(dir);dir.normalize();const mesh=makePencil();mesh.position.copy(camera.position).add(dir.clone().multiplyScalar(.8)).add(new THREE.Vector3(0,-.12,0));mesh.quaternion.setFromUnitVectors(new THREE.Vector3(1,0,0),dir);scene.add(mesh);projectiles.push({mesh,velocity:dir.multiplyScalar(24),life:1.8});}
function removeProjectile(p){const i=projectiles.indexOf(p);if(i>=0)projectiles.splice(i,1);p.mesh.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose();});scene.remove(p.mesh);}
function onEnemyDefeated(enemy){const type=enemy.type;removeEnemy(enemy);score++;if(type==='erling'){erlingKills++;spawnWave(2,true);if(erlingKills%5===0)createGunnar();if(erlingKills>=50&&!magicCircleTriggered){magicCircleTriggered=true;spawnMagicCircle();}}updateHUD();}
function hitEnemy(enemy){enemy.hp--;if(enemy.hp<=0){onEnemyDefeated(enemy);return;}if(enemy.type==='gunnar'){feedbackEl.textContent=`GUNNAR: ${enemy.hp} af 3 træffere tilbage!`;feedbackEl.className='feedback bad';enemy.body.material.color.set(0xff9d8f);setTimeout(()=>{if(enemies.includes(enemy))enemy.body.material.color.set(0xffffff);},120);}}
function updateProjectiles(dt){for(const p of [...projectiles]){p.mesh.position.addScaledVector(p.velocity,dt);p.life-=dt;const sphere=new THREE.Sphere(p.mesh.position,.32);if(colliders.some(c=>c.intersectsSphere(sphere))||p.life<=0){removeProjectile(p);continue;}let hit=null;for(const enemy of enemies){const pos=enemy.group.position.clone();pos.y=1.65;const radius=enemy.type==='gunnar'?1.28:1.05;if(p.mesh.position.distanceTo(pos)<radius){hit=enemy;break;}}if(hit){removeProjectile(p);hitEnemy(hit);}}}

function spawnMagicCircle(){const group=new THREE.Group();group.position.set(0,.035,0);const glow=new THREE.MeshBasicMaterial({color:0x66e7ff,transparent:true,opacity:.82,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending});const ring=new THREE.Mesh(new THREE.RingGeometry(1.55,2.35,64),glow);ring.rotation.x=-Math.PI/2;group.add(ring);const inner=new THREE.Mesh(new THREE.TorusGeometry(1.22,.055,12,64),new THREE.MeshBasicMaterial({color:0xffe86a,transparent:true,opacity:.95,depthWrite:false,blending:THREE.AdditiveBlending}));inner.rotation.x=Math.PI/2;group.add(inner);for(let i=0;i<8;i++){const a=i/8*Math.PI*2,dot=new THREE.Mesh(new THREE.CircleGeometry(.16,20),new THREE.MeshBasicMaterial({color:i%2?0x8ef4ff:0xffdf68,transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));dot.rotation.x=-Math.PI/2;dot.position.set(Math.cos(a)*1.88,.02,Math.sin(a)*1.88);group.add(dot);}const beam=new THREE.Mesh(new THREE.CylinderGeometry(1.45,2.2,4.7,48,1,true),new THREE.MeshBasicMaterial({color:0x73eaff,transparent:true,opacity:.085,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));beam.position.y=2.35;group.add(beam);const light=new THREE.PointLight(0x79eaff,3.1,9);light.position.y=1.5;group.add(light);scene.add(group);magicCircle={group,ring,inner,light};feedbackEl.textContent='EN MAGISK CIRKEL ER OPSTÅET! Gå ind i den.';feedbackEl.className='feedback good';}
function removeMagicCircle(){if(!magicCircle)return;magicCircle.group.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose();});scene.remove(magicCircle.group);magicCircle=null;}
function startDivisionChallenge(now){if(!magicCircle||divisionChallenge?.active)return;campBoost=false;campMovementStartedAt=0;divisionChallenge={active:true,index:0,correct:0,endsAt:now+10000};mathKickerEl.textContent='MAGISK DIVISION · 1/3';problem=divisionProblem();problemEl.textContent=problem.expression;answer='';answerEl.textContent='_';feedbackEl.textContent='10,0 sekunder · Alle fjender er frosset!';feedbackEl.className='feedback good';}
function nextDivisionProblem(){divisionChallenge.index++;if(divisionChallenge.correct>=3){finishDivisionChallenge(true);return;}problem=divisionProblem();mathKickerEl.textContent=`MAGISK DIVISION · ${divisionChallenge.index+1}/3`;problemEl.textContent=problem.expression;answer='';answerEl.textContent='_';}
function finishDivisionChallenge(success){if(!divisionChallenge?.active)return;divisionChallenge.active=false;removeMagicCircle();lastPlayerMoveAt=performance.now();if(success){lives++;updateHUD();mathKickerEl.textContent='EKSTRA LIV!';problemEl.textContent='+1 ♥';feedbackEl.textContent='Tre divisioner på under 10 sekunder!';feedbackEl.className='feedback good';}else{mathKickerEl.textContent='TIDEN GIK';problemEl.textContent='0 ♥';feedbackEl.textContent='Fjenderne bevæger sig igen.';feedbackEl.className='feedback bad';}setTimeout(()=>{if(gameActive)newProblem();},850);}
function submitDivisionAnswer(){if(!divisionChallenge?.active||!answer)return;if(Number(answer)===problem.answer){divisionChallenge.correct++;answer='';answerEl.textContent='_';nextDivisionProblem();}else{feedbackEl.textContent='Forkert. Samme stykke igen · tiden løber!';feedbackEl.className='feedback bad';answer='';answerEl.textContent='_';}}

function playerBlocked(next){const sphere=new THREE.Sphere(new THREE.Vector3(next.x,1,next.z),PLAYER_R);return colliders.some(c=>c.intersectsSphere(sphere));}function enemyBlocked(next){const sphere=new THREE.Sphere(new THREE.Vector3(next.x,1,next.z),.5);return colliders.some(c=>c.intersectsSphere(sphere));}
function updateHUD(){livesEl.textContent='♥ '.repeat(lives).trim()||'0';ammoEl.textContent=ammo;scoreEl.textContent=score;}function flash(id){const el=document.getElementById(id);el.classList.remove('flash');void el.offsetWidth;el.classList.add('flash');}
function hurt(enemy){const now=performance.now();if(now<invulnerableUntil||divisionChallenge?.active)return;invulnerableUntil=now+1200;lives--;flash('damage-flash');updateHUD();if(enemy?.type==='gunnar'){enemy.group.position.copy(pickSpawnPosition());}else if(enemy)removeEnemy(enemy);if(lives<=0){gameActive=false;controls.unlock();document.getElementById('final-score').textContent=score;document.getElementById('game-over').classList.add('open');return;}if(enemies.length===0)spawnWave(1,true);}
function submitAnswer(){if(divisionChallenge?.active){submitDivisionAnswer();return;}if(!problem||!answer)return;if(Number(answer)===problem.answer){ammo++;feedbackEl.textContent='KORREKT! +1 BLYANT ✎';feedbackEl.className='feedback good';updateHUD();setTimeout(()=>{if(gameActive&&!divisionChallenge?.active)newProblem();},420);}else{feedbackEl.textContent='Forkert. Prøv igen.';feedbackEl.className='feedback bad';answer='';answerEl.textContent='_';}}

function updateCamping(now,moved){if(divisionChallenge?.active){lastPlayerMoveAt=now;campMovementStartedAt=0;return;}if(moved){lastPlayerMoveAt=now;if(campBoost){if(!campMovementStartedAt)campMovementStartedAt=now;if(now-campMovementStartedAt>=2000){campBoost=false;campMovementStartedAt=0;feedbackEl.textContent='Du slap væk fra camping-straffen.';feedbackEl.className='feedback good';}}return;}campMovementStartedAt=0;if(!campBoost&&enemies.some(e=>e.type==='erling')&&now-lastPlayerMoveAt>=5000){campBoost=true;speakLine('Du CAMPER! Jeg HAR dig!',{rate:.9,pitch:.62,volume:1});feedbackEl.textContent='CAMPING! Erling løber nu 3× hurtigere. Bevæg dig i 2 sekunder!';feedbackEl.className='feedback bad';}}

addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyM'&&!e.repeat){toggleMusic();return;}if(e.code==='Space'&&onGround&&gameActive){vy=6.4;onGround=false;e.preventDefault();}if(/^Digit\d$/.test(e.code)&&gameActive){if(answer.length<3){answer+=e.key;answerEl.textContent=answer;}}if(e.code==='Backspace'&&gameActive){answer=answer.slice(0,-1);answerEl.textContent=answer||'_';}if(e.code==='Enter'&&gameActive)submitAnswer();});
addEventListener('keyup',e=>keys[e.code]=false);addEventListener('mousedown',e=>{if(e.button===0)firePencil();});canvas.addEventListener('click',()=>{if(gameActive&&!controls.isLocked)controls.lock();});controls.addEventListener('lock',()=>document.getElementById('pointer-note').classList.remove('show'));controls.addEventListener('unlock',()=>{if(gameActive)document.getElementById('pointer-note').classList.add('show');});
function resetGame(){lives=5;ammo=0;score=0;erlingKills=0;campBoost=false;campMovementStartedAt=0;lastPlayerMoveAt=performance.now();magicCircleTriggered=false;divisionChallenge=null;removeMagicCircle();camera.position.set(0,EYE,18);updateHUD();clearEnemies();newProblem();spawnWave(1,true);}
startButton.addEventListener('click',()=>{if(!erlingTexture){loadErling();return;}document.getElementById('start-overlay').classList.remove('open');gameActive=true;ensureMusic();audioCtx?.resume();resetGame();controls.lock();});document.getElementById('restart-button').addEventListener('click',()=>{document.getElementById('game-over').classList.remove('open');gameActive=true;ensureMusic();audioCtx?.resume();resetGame();controls.lock();});

function update(dt,time){if(!gameActive)return;const old=camera.position.clone();const speed=5.4;let dx=0,dz=0;if(keys.KeyW)dz-=1;if(keys.KeyS)dz+=1;if(keys.KeyA)dx-=1;if(keys.KeyD)dx+=1;if(dx||dz){const len=Math.hypot(dx,dz);dx/=len;dz/=len;const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();const right=new THREE.Vector3().crossVectors(forward,new THREE.Vector3(0,1,0)).normalize();const move=forward.multiplyScalar(-dz*speed*dt).add(right.multiplyScalar(dx*speed*dt));const nx=old.clone().add(new THREE.Vector3(move.x,0,0));if(!playerBlocked(nx))camera.position.x=nx.x;const nz=camera.position.clone().add(new THREE.Vector3(0,0,move.z));if(!playerBlocked(nz))camera.position.z=nz.z;}vy-=17*dt;camera.position.y+=vy*dt;if(camera.position.y<=EYE){camera.position.y=EYE;vy=0;onGround=true;}const moved=Math.hypot(camera.position.x-old.x,camera.position.z-old.z)>.012;updateCamping(time,moved);
  if(magicCircle){magicCircle.group.rotation.y+=dt*.75;magicCircle.inner.rotation.z-=dt*1.4;magicCircle.light.intensity=2.7+Math.sin(time*.006)*.7;if(!divisionChallenge?.active&&new THREE.Vector2(camera.position.x-magicCircle.group.position.x,camera.position.z-magicCircle.group.position.z).length()<2.05)startDivisionChallenge(time);}
  if(divisionChallenge?.active){const left=Math.max(0,divisionChallenge.endsAt-time);feedbackEl.textContent=`${(left/1000).toFixed(1).replace('.',',')} sekunder · ${divisionChallenge.correct}/3 korrekte`;feedbackEl.className='feedback good';if(left<=0)finishDivisionChallenge(false);}else{
    for(const enemy of [...enemies]){if(!enemies.includes(enemy))continue;const ep=enemy.group.position,previousX=ep.x,previousZ=ep.z,toPlayer=new THREE.Vector3(camera.position.x-ep.x,0,camera.position.z-ep.z),dist=toPlayer.length();if(dist>.01){toPlayer.normalize();let enemySpeed=enemy.speed||1.35;if(enemy.type==='erling'&&campBoost)enemySpeed*=3;const step=toPlayer.multiplyScalar(enemySpeed*dt),nx=ep.clone().add(new THREE.Vector3(step.x,0,0)),nz=ep.clone().add(new THREE.Vector3(0,0,step.z));if(!enemyBlocked(nx))ep.x=nx.x;if(!enemyBlocked(nz))ep.z=nz.z;}const distanceMoved=Math.hypot(ep.x-previousX,ep.z-previousZ);if(enemy.type==='gunnar')animateGunnar(enemy,dt,time,distanceMoved);else animateErling(enemy,dt,time,distanceMoved);enemy.group.lookAt(camera.position.x,0,camera.position.z);if(dist<1.15)hurt(enemy);}maybeSpeakWhileMoving(time);
  }updateProjectiles(dt);
}
function loop(t){const dt=Math.min((t-last)/1000,.04);last=t;update(dt,t);renderer.render(scene,camera);requestAnimationFrame(loop);}requestAnimationFrame(loop);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});updateHUD();
